name: Render CV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify a Python version compatible with rendercv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rendercv

      - name: Render CV
        run: rendercv render Ravi_Ramakrishnan_Athmanathan_CV.yaml

  build_and_publish_main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify a Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rendercv

      - name: Render CV
        run: rendercv render Ravi_Ramakrishnan_Athmanathan_CV.yaml

      # Optional: Upload artifact (e.g., the PDF or HTML output)
      - name: Upload CV artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-cv
          path: | # Add paths to your rendered CV files, e.g.
            rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV.pdf
            rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV.html
            rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV.md
            rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV.typ
