name: Render CV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify a Python version compatible with rendercv

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "rendercv[full]"

      - name: Render CV (Ravi)
        run: rendercv render Ravi_Ramakrishnan_Athmanathan_CV.yaml

      - name: Render CV (Harshi)
        run: rendercv render Harshitha_CV.yaml

  build_and_publish_main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify a Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "rendercv[full]"

      - name: Render CV (Ravi)
        run: rendercv render Ravi_Ramakrishnan_Athmanathan_CV.yaml

      - name: Render CV (Harshi)
        run: rendercv render Harshitha_CV.yaml

      - name: Update image links in README.md for cache busting
        run: |
          # Get the current commit SHA
          COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7) # Use short SHA for brevity
          # Replace image links in README.md
          # This sed command looks for markdown image links to png files in rendercv_output/
          # and appends ?v=<short_sha> to them.
          # It handles cases where a query string might already exist by removing it first.
          sed -i -E "s|(rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV_[0-9]+\.png)(\?[^)]*)?|\1?v=${COMMIT_SHA}|g" README.md
          echo "Updated image links in README.md with ?v=${COMMIT_SHA}"

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit rendered CV files
        run: |
          git add rendercv_output/
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit in rendercv_output."
          else
            git commit -m "Update rendered CV files [skip ci]"
            echo "Committed changes in rendercv_output."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: false 

      # Optional: Upload artifact (e.g., the PDF or HTML output)
      - name: Upload CV artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-cv
          path: | # Add paths to your rendered CV files, e.g.
            rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV.pdf
            rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV.html
            rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV.md
            rendercv_output/Ravi_Ramakrishnan_Athmanathan_CV.typ
